export const rsvpEndpoints = {
  getInvitees: `/rsvp/invitees`,
  getInviteeByCode: (secretCode: string) => `/rsvp/invitee/${secretCode}`,
  validateRsvpCode: (secretCode: string) => `/rsvp/validate/${secretCode}`,
  createInvitee: `/rsvp/invitees`,
  bulkCreateInvitees: `/rsvp/invitees/bulk`,
  updateInvitee: (id: string) => `/rsvp/invitees/${id}`,
  deleteInvitee: (id: string) => `/rsvp/invitees/${id}`,
  bulkDeleteInvitees: `/rsvp/invitees/bulk-delete`,
  bulkUpdateInviteeStatus: `/rsvp/invitees/bulk-update-status`,
  respondToRsvp: (secretCode: string) => `/rsvp/respond/${secretCode}`,
  getStats: `/rsvp/stats`,
  getMessages: (giftListId: number) => `/rsvp/messages/${giftListId}`,
  updateMessages: `/rsvp/messages`,
  getCustomFields: (giftListId: number) => `/rsvp/custom-fields/${giftListId}`,
  createCustomField: `/rsvp/custom-fields`,
  updateCustomField: (id: number) => `/rsvp/custom-fields/${id}`,
  deleteCustomField: (id: number) => `/rsvp/custom-fields/${id}`,
  getCustomFieldResponses: `/rsvp/custom-field-responses`,
};
