import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedPredesignedLists() {
  console.log('🌱 Seeding predesigned lists...');

  const lists = [
    {
      name: 'Luna de Miel en Italia',
      description: 'Explora la costa de Amalfi, Roma, Florencia y Venecia',
      imageUrl:
        'https://images.unsplash.com/photo-1675267374972-45358f240163?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpdGFsaWFuJTIwY29hc3QlMjBhbWFsZml8ZW58MXx8fHwxNzYwOTY4NzQzfDA&ixlib=rb-4.1.0&q=80&w=1080',
      icon: 'MapPin',
      order: 0,
      gifts: [
        {
          title: 'Vuelos Redondos a Roma',
          description: 'Boletos de avión para dos personas con clase económica premium',
          price: 18000,
          categories: ['Transporte'],
          imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 0,
        },
        {
          title: 'Hotel en la Costa de Amalfi',
          description: 'Estancia de 3 noches en hotel boutique con vista al mar',
          price: 12000,
          categories: ['Alojamiento'],
          imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 1,
        },
        {
          title: 'Tour por los Viñedos de Toscana',
          description: 'Día completo de cata de vinos y recorrido por la campiña',
          price: 4500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=300&h=300&fit=crop',
          priority: 'media',
          order: 2,
        },
        {
          title: 'Cena Romántica en Venecia',
          description: 'Cena gourmet para dos con vista al Gran Canal',
          price: 3500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=300&h=300&fit=crop',
          priority: 'media',
          order: 3,
        },
        {
          title: 'Paseo en Góndola',
          description: 'Recorrido privado por los canales de Venecia',
          price: 2000,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=300&h=300&fit=crop',
          priority: 'baja',
          order: 4,
        },
        {
          title: 'Tour del Coliseo Romano',
          description: 'Visita guiada con acceso prioritario',
          price: 1500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=300&h=300&fit=crop',
          priority: 'media',
          order: 5,
        },
      ],
    },
    {
      name: 'Luna de Miel en Hawái',
      description: 'Playas paradisíacas, volcanes y cultura hawaiana',
      imageUrl:
        'https://images.unsplash.com/photo-1561161168-5c7f75872f18?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYXdhaWklMjB0cm9waWNhbCUyMGJlYWNofGVufDF8fHx8MTc2MDk2ODc0M3ww&ixlib=rb-4.1.0&q=80&w=1080',
      icon: 'Plane',
      order: 1,
      gifts: [
        {
          title: 'Vuelos a Honolulu',
          description: 'Boletos redondos para dos personas con escala',
          price: 22000,
          categories: ['Transporte'],
          imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 0,
        },
        {
          title: 'Resort Frente al Mar',
          description: '5 noches en resort todo incluido en Maui',
          price: 28000,
          categories: ['Alojamiento'],
          imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 1,
        },
        {
          title: 'Snorkel en Bahía de Hanauma',
          description: 'Tour guiado de snorkel con equipo incluido',
          price: 2500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=300&h=300&fit=crop',
          priority: 'media',
          order: 2,
        },
        {
          title: 'Tour de Volcanes',
          description: 'Excursión al Parque Nacional de los Volcanes',
          price: 3500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1618167851446-c2b45e0d2cd2?w=300&h=300&fit=crop',
          priority: 'media',
          order: 3,
        },
        {
          title: 'Luau Hawaiano',
          description: 'Cena tradicional con espectáculo de danza',
          price: 2800,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=300&h=300&fit=crop',
          priority: 'baja',
          order: 4,
        },
        {
          title: 'Clases de Surf',
          description: 'Lecciones privadas de surf en Waikiki',
          price: 2000,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=300&h=300&fit=crop',
          priority: 'baja',
          order: 5,
        },
      ],
    },
    {
      name: 'Luna de Miel en Bali',
      description: 'Templos sagrados, arrozales y playas tropicales',
      imageUrl:
        'https://images.unsplash.com/photo-1656247203824-3d6f99461ba4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWxpJTIwcmljZSUyMHRlcnJhY2VzfGVufDF8fHx8MTc2MDg0Njc0M3ww&ixlib=rb-4.1.0&q=80&w=1080',
      icon: 'Sparkles',
      order: 2,
      gifts: [
        {
          title: 'Vuelos a Denpasar',
          description: 'Boletos internacionales ida y vuelta para dos',
          price: 24000,
          categories: ['Transporte'],
          imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 0,
        },
        {
          title: 'Villa Privada en Ubud',
          description: '4 noches en villa con piscina infinita',
          price: 15000,
          categories: ['Alojamiento'],
          imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 1,
        },
        {
          title: 'Retiro de Yoga y Spa',
          description: 'Día completo de relajación y bienestar',
          price: 3500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=300&h=300&fit=crop',
          priority: 'media',
          order: 2,
        },
        {
          title: 'Tour de Templos',
          description: 'Visita guiada a los templos más sagrados',
          price: 2500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=300&h=300&fit=crop',
          priority: 'media',
          order: 3,
        },
        {
          title: 'Clase de Cocina Balinesa',
          description: 'Aprende a cocinar platillos tradicionales',
          price: 1800,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=300&fit=crop',
          priority: 'baja',
          order: 4,
        },
        {
          title: 'Excursión a Arrozales',
          description: 'Caminata por las terrazas de arroz de Tegallalang',
          price: 1500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=300&h=300&fit=crop',
          priority: 'baja',
          order: 5,
        },
      ],
    },
    {
      name: 'Viaje a Islandia',
      description: 'Auroras boreales, glaciares y aguas termales',
      imageUrl:
        'https://images.unsplash.com/photo-1488415032361-b7e238421f1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpY2VsYW5kJTIwbm9ydGhlcm4lMjBsaWdodHN8ZW58MXx8fHwxNzYwOTMwNTYyfDA&ixlib=rb-4.1.0&q=80&w=1080',
      icon: 'Heart',
      order: 3,
      gifts: [
        {
          title: 'Vuelos a Reikiavik',
          description: 'Boletos de avión redondos con conexión',
          price: 26000,
          categories: ['Transporte'],
          imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 0,
        },
        {
          title: 'Hotel en Reikiavik',
          description: '3 noches en hotel céntrico',
          price: 9000,
          categories: ['Alojamiento'],
          imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 1,
        },
        {
          title: 'Tour del Círculo Dorado',
          description: 'Día completo visitando Geysir, Gullfoss y Þingvellir',
          price: 4500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=300&h=300&fit=crop',
          priority: 'media',
          order: 2,
        },
        {
          title: 'Entrada a la Laguna Azul',
          description: 'Acceso premium con toallas y bebida',
          price: 3000,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1557429287-b2e26467fc2b?w=300&h=300&fit=crop',
          priority: 'media',
          order: 3,
        },
        {
          title: 'Tour de Auroras Boreales',
          description: 'Excursión nocturna para ver las luces del norte',
          price: 3500,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1579033461380-adb47c3eb938?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 4,
        },
        {
          title: 'Caminata en Glaciar',
          description: 'Trekking guiado en el glaciar Sólheimajökull',
          price: 4000,
          categories: ['Experiencias'],
          imageUrl: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=300&h=300&fit=crop',
          priority: 'media',
          order: 5,
        },
      ],
    },
    {
      name: 'Redecoración del Hogar',
      description: 'Actualiza tu espacio actual con estilo moderno',
      imageUrl:
        'https://images.unsplash.com/photo-1600210492493-0946911123ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBob21lJTIwaW50ZXJpb3J8ZW58MXx8fHwxNzYwODk5MjYyfDA&ixlib=rb-4.1.0&q=80&w=1080',
      icon: 'Palette',
      order: 4,
      gifts: [
        {
          title: 'Sofá Moderno de 3 Plazas',
          description: 'Sofá tapizado en tela de alta calidad color gris',
          price: 15000,
          categories: ['Sala'],
          imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 0,
        },
        {
          title: 'Mesa de Centro Minimalista',
          description: 'Mesa de madera natural con acabado mate',
          price: 4500,
          categories: ['Sala'],
          imageUrl: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=300&h=300&fit=crop',
          priority: 'media',
          order: 1,
        },
        {
          title: 'Lámpara de Piso Moderna',
          description: 'Lámpara tipo arco con base de mármol',
          price: 3200,
          categories: ['Iluminación'],
          imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=300&h=300&fit=crop',
          priority: 'media',
          order: 2,
        },
        {
          title: 'Set de Cojines Decorativos',
          description: 'Paquete de 4 cojines en tonos neutros',
          price: 1200,
          categories: ['Decoración'],
          imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=300&h=300&fit=crop',
          priority: 'baja',
          order: 3,
        },
        {
          title: 'Espejo Decorativo Grande',
          description: 'Espejo de pared con marco dorado',
          price: 2800,
          categories: ['Decoración'],
          imageUrl: 'https://images.unsplash.com/photo-1618220179428-22790b461013?w=300&h=300&fit=crop',
          priority: 'media',
          order: 4,
        },
        {
          title: 'Alfombra de Sala Grande',
          description: 'Alfombra tejida 2x3 metros estilo contemporáneo',
          price: 5500,
          categories: ['Decoración'],
          imageUrl: 'https://images.unsplash.com/photo-1600166898405-da9535204843?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 5,
        },
      ],
    },
    {
      name: 'Hogar Nuevo',
      description: 'Equipa tu nueva casa con todo lo esencial',
      imageUrl:
        'https://images.unsplash.com/photo-1581573950452-5a438c5f390f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuZXclMjBob21lJTIwbW92aW5nfGVufDF8fHx8MTc2MDk2ODc0NHww&ixlib=rb-4.1.0&q=80&w=1080',
      icon: 'Home',
      order: 5,
      gifts: [
        {
          title: 'Juego de Comedor para 6 Personas',
          description: 'Mesa y 6 sillas en madera maciza',
          price: 18000,
          categories: ['Comedor'],
          imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 0,
        },
        {
          title: 'Refrigerador de 18 pies',
          description: 'Refrigerador acero inoxidable con dispensador',
          price: 15000,
          categories: ['Electrodomésticos'],
          imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 1,
        },
        {
          title: 'Lavadora Automática',
          description: 'Lavadora de 20 kg con múltiples programas',
          price: 9500,
          categories: ['Electrodomésticos'],
          imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=300&h=300&fit=crop',
          priority: 'alta',
          order: 2,
        },
        {
          title: 'Microondas Gourmet',
          description: 'Microondas de 1.5 pies cúbicos con grill',
          price: 3500,
          categories: ['Electrodomésticos'],
          imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=300&h=300&fit=crop',
          priority: 'media',
          order: 3,
        },
        {
          title: 'Juego de Ollas Premium',
          description: 'Set de 12 piezas acero inoxidable',
          price: 4500,
          categories: ['Cocina'],
          imageUrl: 'https://images.unsplash.com/photo-1584990347449-39b7e93c2cdb?w=300&h=300&fit=crop',
          priority: 'media',
          order: 4,
        },
        {
          title: 'Vajilla Completa',
          description: 'Servicio para 12 personas porcelana blanca',
          price: 3200,
          categories: ['Cocina'],
          imageUrl: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=300&h=300&fit=crop',
          priority: 'media',
          order: 5,
        },
      ],
    },
  ];

  for (const list of lists) {
    const { gifts, ...listData } = list;

    await prisma.predesignedList.upsert({
      where: { name: list.name },
      update: {},
      create: {
        ...listData,
        gifts: {
          create: gifts,
        },
      },
    });
  }

  console.log('✅ Predesigned lists seeded successfully');
}
