export const queryKeys = {
  gifts: 'gifts',
  giftsByWeddingList: 'giftsByWeddingList',
  purchasedGifts: 'purchasedGifts',
  userPurchases: 'userPurchases',
  weddingLists: 'weddingLists',
  weddingListByCouple: 'weddingListByCouple',
  weddingListBySlug: 'weddingListBySlug',
  cart: 'cart',
  cartItems: 'cartItems',
  payments: 'payments',
  paymentSummary: 'paymentSummary',
  users: 'users',
  currentUser: 'currentUser',
  userBySlug: 'userBySlug',
  categories: 'categories',
  categoriesByWeddingList: 'categoriesByWeddingList',
  uploadFile: 'uploadFile',
};
